### PR TITLE
feat: add entry to helpdesk in menu

### PR DESCRIPTION
**Pull request by LeonVreling**
This is a hacky way of doing what we want to achieve. Router is not meant to redirect you to external pages, so that is why this solution was made. 

In the future, this page can be used to integrate the helpdesk fully into MyAEGEE, like was also done for the legal stuff.

### CODE REVIEW

**Comment by linuxbandit** [comment]
uu nice, can't wait to try it out

**Review by linuxbandit — APPROVED** [review]

**Review by serge1peshcoff — CHANGES_REQUESTED** [review]
We can make it displaying real link without real components, I'll elaborate in 30', don't merge it yet

**Comment by serge1peshcoff** [comment]
@LeonVreling okay what I suggest you to do is:
1) check out `frontend/src/components/layout/Sidebar.vue`, there's a `v-if` on line 8 and `v-else` on line 16, the idea is: it either displays the menu entry as a router link, or as a button which unfolds and shows its children when you click it. You can change the `v-else` on line 16 to `v-else-if="!item.link"`, then add another `<a :hrev="item.link" target="_blank" v-else>` after it, this way you won't need the extra component and the link would directly lead to whatever you need.
2) in the `frontend/src/menu.json`, in the object with link you just specify the `link` field
3) also you need to add the `link` field processing to `frontend/src/store/modules/menu.js` for this to work, basically adding 

```
link: component.link,
```
to `mapComponent` should do

This way you won't need the extra component to redirect

**Comment by LeonVreling** [comment]
@serge1peshcoff I did the things that you suggested, and it works even better now!

**Review by serge1peshcoff — APPROVED** [review]
Yeah, this should work, thanks!

**Pull request merged**
