### PR TITLE
Add support for Firefox 68 (Extended Support Release)

### PR DESCRIPTION
**Pull request by dilyanpalauzov**
by deleting `.browserslistrc` and relaying on the defaults.

### CODE REVIEW

**Comment by dilyanpalauzov** [comment]
I have some doubts.  When the file .browserslist is missing, the software `browserslist` assumes that the `defaults` was present in the `.browserslist` file.  The conversions (necessary transforms/transpilings) are done by Babel, in particular `@babel/preset-env`.

Its [documentation states](https://babeljs.io/docs/en/babel-preset-env#browserslist-integration):
> By default @babel/preset-env will use browserslist config sources unless either the targets or ignoreBrowserslistConfig options are set.

So, what will happen, if `targets` and `ignoreBrowserslistConfig` are not set and `.browserslist` does not exist?  Well, missing `targets` is [documented](https://babeljs.io/docs/en/babel-preset-env#targets) as:
> Sidenote, if no targets are specified, @babel/preset-env will transform all ECMAScript 2015+ code by default.

I asked at https://github.com/babel/website/issues/2245 what does this mean, in particular what happens, when `.browserslist`, `targets:` and `ignoreBrowserslistConfig` are missing.  A possible reading of the communication is, that under all these circumstances, the code is ES2020-ready, meaning it is not transpiled and does not run on IE 11 and such very important browsers.

**Comment by dilyanpalauzov** [comment]
See also:
• https://github.com/vuejs/vue-cli/issues/5487: the [documentation of `@vue/babel-preset-app`](https://github.com/vuejs/vue-cli/tree/dev/packages/%40vue/babel-preset-app) does not state, that it reads the `.browserslist` file, but only the information from `package.json`.
• https://github.com/vuejs/vue-cli/issues/5488: the documentation of `@vue/babel-preset-app` is not clear what a missing `.browserslist` file (or a corresponding entry in `package.json`) means.

**Comment by WikiRik** [comment]
Why don't we set it to`defaults`? That is the same as `> 0.5%, last 2 versions, Firefox ESR, not dead` according to the [README of browserslist](https://github.com/browserslist/browserslist)

**Pull request merged**
