### PR TITLE
fix(markdown): Remove styling of bold text. Fixes HELP-1315

### PR DESCRIPTION
**Pull request by WikiRik**

### CODE REVIEW

**Review by serge1peshcoff — APPROVED** [review]

**Comment by WikiRik** [comment]
@serge1peshcoff I will merge this later today, will give Leon a chance to improve this first. Since we want the bold text in the markdown tooltip to be white, but not for the other parts where we use markdown.
@LeonVreling other option is of course to not include Markdown in the tooltip ;)

**Comment by serge1peshcoff** [comment]
do we need Markdown in tooltips in general though? I am unsure as I don't know a case when we need in there (maybe others do)

**Comment by WikiRik** [comment]
No, but Leon liked to have markdown in the markdown tooltip. But that has an unintended side-effect so Leon will have to find a fix for it

**Comment by WikiRik** [comment]
Superseded by #620

**Pull request closed without merging**
