### PR TITLE
chore(login): Remove warning message about new core

### PR DESCRIPTION
**Pull request by WikiRik**

### CODE REVIEW

**Review by serge1peshcoff — APPROVED** [review]

**Comment by linuxbandit** [comment]
is there a way to have this warning as component, and reuse it with different text? Does it make sense? @WikiRik @serge1peshcoff

**Comment by WikiRik** [comment]
For this use or just in general for the warning boxes that we have in MyAEGEE?

**Comment by linuxbandit** [comment]
for uses in general, where we may need to tell user a certain something

**Comment by linuxbandit** [comment]
also why did the release-bot start only 40 minutes ago if it was merged before?

**Comment by WikiRik** [comment]
@linuxbandit chores do not count for semver so are also handled by release-bot until a new version is being made. Then it will include that message on all chores that were also done in the new version (mostly dependencies)

**Pull request merged**
