### PR TITLE
fix(docker): dockerfile fixes

### PR DESCRIPTION
**Pull request by serge1peshcoff**
removed a few extra steps when building the docker image, should save us some time.

### CODE REVIEW

**Comment by WikiRik** [comment]
Why did we decide to use an extra user instead of root in the first place? And is it preferable to use root for this?

**Comment by serge1peshcoff** [comment]
1) no idea, this whole dockerfile is a copypase of the one from oms-central-frontend (a legacy thing before frontend and oms-frontend with angular 1.x as a framework), so I've never thought about it
2) that way we won't need an extra step for chown'ing all stuff. Also, security-wise, it shouldn't matter which user we use inside, as this user can only access and modify files in the docker container sandbox (and files from the host machine shouldn't be mounted in production).

**Review by linuxbandit — COMMENTED** [review]
I am not convinced about this, running a container as root is not great (I think I put the `????` on the commented line about user being www-data i.e. the line was commented out, and I added the `???` as a FIXME to investigate why we were running a container as root

**Comment by serge1peshcoff** [comment]
then we can leave it as it is I assume? @linuxbandit

**Comment by linuxbandit** [comment]
if anything, I'd re-add `USER www-data`

**Comment by WikiRik** [comment]
@serge1peshcoff fine if we close this?

**Pull request closed without merging**
