### PR TITLE
fix(statutory): refer to KMS page instead of booklet. Fixes HELP-2399

### PR DESCRIPTION
**Pull request by WikiRik**
Also updates the deadline of publishing the updated page to 5 days in advance, per WF of the Agora Article 15 (3)

### CODE REVIEW

**Comment by WikiRik** [comment]
When sending a message to Niklas I did wonder one thing; this will affect all statutory events, but former statutory events (until EPM Eindhoven) actually used a booklet folder. Maybe it's better to make it a separate field in the database? Then we would have two things that basically do the same though. What do you think? @LeonVreling

**Comment by WikiRik** [comment]
Note to me; I think the KMS page is also useful before the publication deadline so it can also be shown then I think. Will discuss with Chair

**Comment by WikiRik** [comment]
Got feedback from Chair as well, drafting this until it's all done again

**Comment by LeonVreling** [comment]
I think that for historic events, we do want to keep the link to the previous document. However, I am not certain how many people actually do look at these historic documents

**Review by LeonVreling — APPROVED** [review]

**Comment by WikiRik** [comment]
I had the idea that we'll have a generic documents deadline but have two different types of links to that. The current booklet link and a new kms link and when creating a new event people can choose one of the two. I'll try to see if I can work on that later this week

**Comment by WikiRik** [comment]
Will work on the above in a later PR, if we end up doing that

**Pull request merged**
