### PR TITLE
feat(user): save privacy consent new users

### PR DESCRIPTION
**Pull request by LeonVreling**
Frontend for issue [MA-48](https://myaegee.atlassian.net/browse/MA-48)

### CODE REVIEW

**Comment by LeonVreling** [comment]
This is still a work in progress, still need to figure out how to do it for existing users (probably with the splash screen)

**Comment by WikiRik** [comment]
I thought we merged this already for existing users, but apparently not. We should not forget to merge this with the others

**Comment by LeonVreling** [comment]
Yes very true, honestly also forgot that it was still a draft 😅

**Comment by LeonVreling** [comment]
I don't see why we can't merge this yet at the moment, should not break anything if we do already

**Comment by WikiRik** [comment]
The Privacy Consent field is already mandatory, right?

**Review by WikiRik — APPROVED** [review]

**Comment by LeonVreling** [comment]
Yes, you can't submit the form unless you have ticked the box

**Pull request merged**
