### PR TITLE
feat(MA-6): add additional fields to events (front)

### PR DESCRIPTION
**Pull request by HassanCehef**
Addition of a few new fields that will be useful for offline events (best time for those :D).
EQAC requested five extra fields

I think a side effect of this is that people editing their current events will be forced to fill two new mandatory fields: accommodation type, and number of meals served.
Both of which do not make sense in the current context where everything happens online.
A further PR will improve the creation of online-only events, where more fields will be hidden.

TODO:
- [x] validate the wording, the help text, and the position of the fields
- [x] fix the SingleView, where fields are printed when they should not.

This must be merged only in sync with the PR on AEGEE/events#314

### CODE REVIEW

**Comment by WikiRik** [comment]
For the validation of the wording, help text and position of the fields; can you make some screenshots and add them to the ticket? And tag Nicoleta in it so she can check it

**Comment by HassanCehef** [comment]
image

**Comment by WikiRik** [comment]
Nicoleta approved the wording and positions.
@HassanCehef what do you need to fix for the SingleView?

**Review by WikiRik — APPROVED** [review]

**Pull request merged**
